<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HL7 Log</name>
   <tag></tag>
   <elementGuidId>777028a2-dc19-4c2d-8eff-3a6bc1e3f07e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.ui-widget-content.ui-menu-list.ui-corner-all.ui-helper-clearfix.ui-menu-child.ui-shadow > li.ui-menuitem.ui-widget.ui-corner-all.ui-menuitem-active > a.ui-menuitem-link.ui-corner-all.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='j_idt11:j_idt25:menubar']/ul/li[6]/ul/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db2e0d93-53c4-4e42-829f-e6f9d1ecc4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6b0fdfb4-f124-4326-8559-4524c3b776c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menuitem-link ui-corner-all ui-state-hover</value>
      <webElementGuid>006fca3b-f225-49e0-a13e-929559d3148e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ROBIN/faces/Pages/Log/LogIndexView.xhtml</value>
      <webElementGuid>29965380-0621-4213-a882-ff91dc11b0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> HL7 Log</value>
      <webElementGuid>98f89581-a0c4-4a5c-8bf2-566e0692f0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt11:j_idt25:menubar&quot;)/ul[@class=&quot;ui-menu-list ui-helper-reset&quot;]/li[@class=&quot;ui-widget ui-menuitem ui-corner-all ui-menu-parent ui-menuitem-active&quot;]/ul[@class=&quot;ui-widget-content ui-menu-list ui-corner-all ui-helper-clearfix ui-menu-child ui-shadow&quot;]/li[@class=&quot;ui-menuitem ui-widget ui-corner-all ui-menuitem-active&quot;]/a[@class=&quot;ui-menuitem-link ui-corner-all ui-state-hover&quot;]</value>
      <webElementGuid>6c0ba89d-b2b9-418a-857f-1388edb734d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j_idt11:j_idt25:menubar']/ul/li[6]/ul/li[7]/a</value>
      <webElementGuid>cd4ad95b-5375-4c75-870e-4381a19573c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Codes Mapping'])[1]/following::a[1]</value>
      <webElementGuid>ea70446a-9d7c-4902-a31e-e029a7737ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinicians'])[1]/following::a[2]</value>
      <webElementGuid>18e3eca2-4985-4ba9-a450-ebce8daf1ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back Office Management'])[1]/preceding::a[1]</value>
      <webElementGuid>362a7674-8103-4c0c-99c5-af29a344722f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ROBIN/faces/Pages/Log/LogIndexView.xhtml')]</value>
      <webElementGuid>28c98616-3b6e-4a1b-968e-86ec41b573bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[7]/a</value>
      <webElementGuid>2d8f8c69-6c1a-4402-be97-a0581be02fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ROBIN/faces/Pages/Log/LogIndexView.xhtml' and (text() = ' HL7 Log' or . = ' HL7 Log')]</value>
      <webElementGuid>10627c2e-c55b-41ce-9a09-c124f1395680</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
