<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter by msgType_LogIndexFormdatalis_6d48b3</name>
   <tag></tag>
   <elementGuidId>5bf3263a-3a54-4ede-b78e-e7dd4f0c7cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LogIndexForm:datalist:j_idt167:filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99f5b1f3-af82-40e3-981b-fe7f4997bcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LogIndexForm:datalist:j_idt167:filter</value>
      <webElementGuid>44d58175-0196-4567-ae24-24e82694937d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LogIndexForm:datalist:j_idt167:filter</value>
      <webElementGuid>290df9fc-a498-4df4-831a-9c00de352e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-column-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>72d297bc-f83e-4944-b685-982716f9e49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>05dfdc8a-0f31-4841-83d2-bff2b7050f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>LogIndexForm:datalist:j_idt167:filter_label</value>
      <webElementGuid>e0eeb96d-b73b-497b-b45e-836f3c385247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>25872680-3602-4cfd-964e-acae9cdd3280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fec42172-9466-4969-b695-cec5c4e2a581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a6d4c718-5f3e-4826-a0c2-46fa9457e158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LogIndexForm:datalist:j_idt167:filter&quot;)</value>
      <webElementGuid>d6454981-d804-4827-a666-347c8b1c9856</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LogIndexForm:datalist:j_idt167:filter']</value>
      <webElementGuid>91b239d5-b2b2-44de-b25a-a0edd0a3c1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='LogIndexForm:datalist:j_idt167']/input</value>
      <webElementGuid>45e39485-8495-4f7e-ae3b-e660d4828214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/input</value>
      <webElementGuid>02b7ef9c-62f4-4551-9652-82647d5e65bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LogIndexForm:datalist:j_idt167:filter' and @name = 'LogIndexForm:datalist:j_idt167:filter']</value>
      <webElementGuid>5ecc5bd2-8b8c-4ac2-a1cb-92f6b8460555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
