<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter by MsgId_LogIndexFormdatalistj_aa02d0</name>
   <tag></tag>
   <elementGuidId>29506bcd-4dea-4c9a-ab89-33921fb68988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LogIndexForm:datalist:j_idt158:filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b00e9bd5-1295-429e-8370-997aa2ad2911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LogIndexForm:datalist:j_idt158:filter</value>
      <webElementGuid>87faf4a1-85b0-4f92-9fc2-1c16d3d6f9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LogIndexForm:datalist:j_idt158:filter</value>
      <webElementGuid>7588197a-ee0c-41df-ac2e-9ab23c1e8736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-column-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>0ebcf09e-e816-4e27-8842-7666e5caa283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3c472270-3757-43aa-82dc-fcc6f81a26e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>LogIndexForm:datalist:j_idt158:filter_label</value>
      <webElementGuid>4ba5b195-db55-4f9f-bca0-ec1bd7671d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>02b15467-c6d4-419a-8bb7-6f8fc8dd087c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cfa64283-f095-4f8d-9322-03b01c234a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ffb6328-bc42-4524-ac11-419f7c9cbb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LogIndexForm:datalist:j_idt158:filter&quot;)</value>
      <webElementGuid>01011888-e83b-4e1b-9144-425d270d5cef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LogIndexForm:datalist:j_idt158:filter']</value>
      <webElementGuid>20a6a4fe-90f7-47d9-8518-603b6b733813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='LogIndexForm:datalist:j_idt158']/input</value>
      <webElementGuid>b9e6da64-637e-416a-9bb7-8afb7b6aa2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/input</value>
      <webElementGuid>85052548-04b2-4e12-b9be-3ccd043bb360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LogIndexForm:datalist:j_idt158:filter' and @name = 'LogIndexForm:datalist:j_idt158:filter']</value>
      <webElementGuid>52f595b9-0230-43fb-b1f5-a2dc21ca28cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
