<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_depart</name>
   <tag></tag>
   <elementGuidId>9c8ee917-ece7-4f85-9267-1c5e228b43e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id=&quot;InvoiceForm:department_label&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>2116394f-9930-4c75-aa37-c7b559cf8366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1669269477463</value>
      <webElementGuid>70b2a266-ea1c-4b54-bb6c-e4fc05f6b122</webElementGuid>
   </webElementProperties>
</WebElementEntity>
