<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_visit type</name>
   <tag></tag>
   <elementGuidId>dc8ee0ab-1c6b-4d8b-8173-0e649c2a063f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id=&quot;InvoiceForm:visit_type_label&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>b36536a4-c177-4218-a976-274c2921ee5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1669269614487</value>
      <webElementGuid>3d0c4f9f-6241-4d89-b322-34341310598c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
