<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_save</name>
   <tag></tag>
   <elementGuidId>3e92c1fd-b349-4973-9e6b-e3a46e7d00c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>bda61280-40e8-40a1-9c7e-81fb604a34ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1669194863206</value>
      <webElementGuid>25ebc992-296c-48b4-8d62-ec9f2c4b8316</webElementGuid>
   </webElementProperties>
</WebElementEntity>
