<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__AccumedPatientInsuranceCreateFormpat_cc52de</name>
   <tag></tag>
   <elementGuidId>11f3ee65-c33b-4558-a9c3-5e4f47c36527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedPatientInsuranceCreateForm:patientInsuranceId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f07ad789-aaac-4578-9f2c-ae2bacff2b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:patientInsuranceId</value>
      <webElementGuid>cdf4fb12-5b23-478b-a14b-875285b1c447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:patientInsuranceId</value>
      <webElementGuid>21470385-52b2-47de-916b-db3a7a538f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a3358cc-1953-4fe3-8fc2-1ee2b354b0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>- The patient's insurance member number, if the patient is claiming insurance.                                              - Otherwise, this field should be left empty.</value>
      <webElementGuid>902feb30-5e86-4165-8711-87606bc38d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus ui-state-hover</value>
      <webElementGuid>cfe9f3c5-2d2a-4331-8c26-013218f88f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c107209d-8d2b-4f4b-8992-2bf41900fcdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2a855a5a-6e09-483d-93fc-33867d3669e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>314b2360-daa6-4baf-aaa6-9d48df589697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientInsuranceCreateForm:patientInsuranceId&quot;)</value>
      <webElementGuid>12760b68-020e-4d96-9cbe-51a5759feea5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedPatientInsuranceCreateForm:patientInsuranceId']</value>
      <webElementGuid>108a2985-e2bb-4e44-813d-5dd49efe6c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AccumedPatientInsuranceCreateForm:j_idt1254']/tbody/tr/td[2]/input</value>
      <webElementGuid>820e201c-e435-45b9-bbb6-9c09bcdd2a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>92b67837-cbfd-4085-bc1d-0f1ecd635ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedPatientInsuranceCreateForm:patientInsuranceId' and @name = 'AccumedPatientInsuranceCreateForm:patientInsuranceId' and @type = 'text' and @title = concat(&quot;- The patient&quot; , &quot;'&quot; , &quot;s insurance member number, if the patient is claiming insurance.                                              - Otherwise, this field should be left empty.&quot;)]</value>
      <webElementGuid>e55bd1dd-510a-4d32-b71d-0d0b6cffef57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
