<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_AccumedPatientCreateFormemail</name>
   <tag></tag>
   <elementGuidId>2abea7eb-61ba-49bd-9396-277cb034d6c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedPatientCreateForm:email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed6d58bb-2f9e-42b7-9fe2-230463d68c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientCreateForm:email</value>
      <webElementGuid>7667f2f7-9f36-42d0-89f5-27181739de93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedPatientCreateForm:email</value>
      <webElementGuid>0869a112-8d95-47c8-9e07-f0d1556d596d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33cc88aa-676c-41d7-922b-bce5a8abb72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>9677c523-edcc-4bda-8562-a97036e087d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>076f71da-da78-4e7c-8896-bd1f986e60f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>52ba6bd1-8096-453c-ae59-29ae9c8a3757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01d19601-e1f7-4d00-88a8-dc23d808d63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientCreateForm:email&quot;)</value>
      <webElementGuid>6746f1a9-0c9b-41ee-9115-522b36819e32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedPatientCreateForm:email']</value>
      <webElementGuid>24623169-34fb-46d3-9e72-4332a73ad4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AccumedPatientCreateForm:j_idt986']/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>26a83653-7a7d-4b94-851e-92b818ae85c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>fe6d2ce5-1693-451c-8730-4d1d37c769e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedPatientCreateForm:email' and @name = 'AccumedPatientCreateForm:email' and @type = 'text']</value>
      <webElementGuid>9562be81-fc5a-4acc-b352-e29fc94023ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
