<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_timeUnit_AccumedHaadActivityListForma_6ca34a</name>
   <tag></tag>
   <elementGuidId>7a49e4b8-24c0-4f5c-80a3-0204eb3c236d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedHaadActivityListForm:activityCode_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>869cfa9d-bc37-4574-8b80-0ef0200c6627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:activityCode_input</value>
      <webElementGuid>44723774-411c-40a6-a68a-0e30475c7b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:activityCode_input</value>
      <webElementGuid>384510a5-59e1-490b-bdbe-49114311a63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d5b7e80-707b-4c7b-a94d-233db30fbd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input ui-inputfield ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>a60ed28c-5251-42fc-b364-a745a4f81233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a3851b06-5068-471d-81d4-57daaef12f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:j_idt1937</value>
      <webElementGuid>feeca9ea-e138-436d-ac24-b34c3b57a870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>2c8bd598-15f7-46f0-a655-38b6ca82463c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedHaadActivityListForm:activityCode&quot;,e:&quot;keypress&quot;,p:&quot;AccumedHaadActivityListForm:activityCode&quot;,u:&quot;AccumedHaadActivityListForm:activityCode AccumedHaadActivityListForm:activityList AccumedHaadActivityListForm:totalPrice AccumedHaadActivityListForm:startDate AccumedHaadActivityListForm:activityClinician AccumedHaadActivityListForm:contractSuspendErrorsRefresh growl AccumedHaadActivityListForm:activityDrugType AccumedHaadActivityListForm:activityDrugTypeLabel&quot;,onst:function(cfg){if(event.keyCode!=9)return false;;}});</value>
      <webElementGuid>2254b6f8-a930-4878-86b4-ad4afc660fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>98c61515-bb47-4e0d-a878-e37e1c7a4aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3abb43e7-d6b9-4179-9966-a019d5d6703f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d6c5f11-0a42-4166-b889-082c2fe26038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b6987354-957d-4c4a-b753-1e9284c7fe86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>ad4eb846-4366-43a8-b94a-5976f0fc88db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:activityCode_input&quot;)</value>
      <webElementGuid>e0c5830f-8d88-4a3c-af6f-4b335a6bd5b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedHaadActivityListForm:activityCode_input']</value>
      <webElementGuid>00c0086f-b8f7-4968-b109-519e88539f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='AccumedHaadActivityListForm:activityCode']/input</value>
      <webElementGuid>a2aad3a7-4f82-4b98-b099-7cecbd1b3721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/form[2]/fieldset/div/span/table/tbody/tr[2]/td/span/input</value>
      <webElementGuid>685cdeea-2bb6-4157-806a-4cc3534baf9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedHaadActivityListForm:activityCode_input' and @name = 'AccumedHaadActivityListForm:activityCode_input' and @type = 'text']</value>
      <webElementGuid>077d0c46-f8eb-42d9-8fb4-c3ca63052c04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
