<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Outpatient - patient not admitted and_1b549c</name>
   <tag></tag>
   <elementGuidId>ccc9d51e-d48c-4684-986a-ee2909e955f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='InvoiceForm:icd_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>efd668f4-acb2-4cf4-9606-54074cf6eded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceForm:icd_label</value>
      <webElementGuid>57ff6f09-924f-42f3-9ac5-b4cd00aa16cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>3545ace4-2961-4ff8-a3f9-b1a3ebae5da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outpatient - patient not admitted and not seen in Emergency
Department</value>
      <webElementGuid>4a67ca9b-c5fc-4096-81ff-ccd7aed7ed13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceForm:icd_label&quot;)</value>
      <webElementGuid>c1028299-3d01-4a10-9ef2-9775a42ab2a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='InvoiceForm:icd_label']</value>
      <webElementGuid>3473baec-de23-435d-9a6c-b6d131bf8f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='InvoiceForm:icd']/label</value>
      <webElementGuid>58b7fe8d-c303-4c11-acd5-8f0c1eca1936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encounter Type:*'])[1]/following::label[1]</value>
      <webElementGuid>a8b0f6a9-9e6f-4c36-a9c4-c65de705bb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date:'])[1]/following::label[1]</value>
      <webElementGuid>fe01803a-eb28-4683-a858-655d69802f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Type:'])[1]/preceding::label[1]</value>
      <webElementGuid>d79a04c5-8f52-470e-9b03-cc4e383253e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::label[1]</value>
      <webElementGuid>a7ac7685-152f-4e3d-a680-df28b1fe82d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td/div/label</value>
      <webElementGuid>c90cfb7f-e9d4-4be4-807f-cd4bffd0f774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'InvoiceForm:icd_label' and (text() = 'Outpatient - patient not admitted and not seen in Emergency
Department' or . = 'Outpatient - patient not admitted and not seen in Emergency
Department')]</value>
      <webElementGuid>eb0ced55-41f3-480a-8e90-b5bf5d6f9b58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
