<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Cardiology</name>
   <tag></tag>
   <elementGuidId>586f7439-5ec8-4f9d-ab66-c5f7becebc0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='InvoiceForm:department_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>97683f82-70a6-4afb-95bb-e072c3524007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>72b0cf34-f5b2-45eb-9605-f1c80c198619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Cardiology</value>
      <webElementGuid>affc3c41-3f79-46e9-a621-80f4d891055c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>20943662-65cb-4902-956a-37d394ed7c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>eab71371-2af5-4b65-85d4-19c8f00e7d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceForm:department_4</value>
      <webElementGuid>6c996f25-3c63-4929-b120-cc3dae061bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cardiology</value>
      <webElementGuid>865a8d45-322f-4761-bd3e-e3c4f5ce7ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceForm:department_4&quot;)</value>
      <webElementGuid>6f4ce16f-0547-4c74-8b96-36a3d6ce11ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='InvoiceForm:department_4']</value>
      <webElementGuid>46485f12-d067-4421-998a-edead5f5ed6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='InvoiceForm:department_items']/li[5]</value>
      <webElementGuid>75d3c7da-e82d-4e10-bb2f-51dc2b5d8b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Trip Check up'])[4]/following::li[1]</value>
      <webElementGuid>df5472e2-4938-42e3-8255-748f7bfc1079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artificial Limbs'])[4]/following::li[2]</value>
      <webElementGuid>be36f400-ea89-4081-8abc-9d7cca93736b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cardiothoracic Surgery'])[4]/preceding::li[1]</value>
      <webElementGuid>67cd4f9e-6b07-40e1-a5d6-7b42083045b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dental'])[14]/preceding::li[2]</value>
      <webElementGuid>bdfd87fd-c029-473c-af6e-8eff18b3ec6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[81]/div/ul/li[5]</value>
      <webElementGuid>a968263d-506b-4f77-999c-f3ddd8e43755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'InvoiceForm:department_4' and (text() = 'Cardiology' or . = 'Cardiology')]</value>
      <webElementGuid>6ed2e9fc-b54f-4eb8-995c-8ec3f3e01590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
