<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Class_ui-button-icon-primary ui-icon u_1ed3f1</name>
   <tag></tag>
   <elementGuidId>6dd82361-33cf-45f5-8bf3-4611e454f3a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='AccumedPatientInsuranceCreateForm:class']/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ui-autocomplete-dropdown.ui-button.ui-widget.ui-state-default.ui-corner-right.ui-button-icon-only.ui-state-hover > span.ui-button-icon-primary.ui-icon.ui-icon-triangle-1-s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7cbeb38-3ff7-400b-a411-13997388683c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-icon-primary ui-icon ui-icon-triangle-1-s</value>
      <webElementGuid>15d0a47f-cfbb-46da-b6eb-cbcf46b1ff30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientInsuranceCreateForm:class&quot;)/button[@class=&quot;ui-autocomplete-dropdown ui-button ui-widget ui-state-default ui-corner-right ui-button-icon-only ui-state-hover&quot;]/span[@class=&quot;ui-button-icon-primary ui-icon ui-icon-triangle-1-s&quot;]</value>
      <webElementGuid>1466c8db-966e-47d4-9560-d0c466b7a509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='AccumedPatientInsuranceCreateForm:class']/button/span</value>
      <webElementGuid>690ecb48-6fd7-48af-bf40-f3c267bcd30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/span/button/span</value>
      <webElementGuid>00675303-4988-4865-afe0-c5302f26b34d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
