<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AMAL  (R) ELSAID</name>
   <tag></tag>
   <elementGuidId>64a69514-2ce4-4d3b-90b2-1f86f9b970b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='InvoiceForm:clinician_panel']/table/tbody/tr[7]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>eb56b9bb-9fb2-4e21-bc41-fe02b20cb272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMAL  (R) ELSAID</value>
      <webElementGuid>6b488f0d-4e7f-4fc6-a647-571c4a3f8830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceForm:clinician_panel&quot;)/table[@class=&quot;ui-autocomplete-items ui-autocomplete-table ui-widget-content ui-widget ui-corner-all ui-helper-reset&quot;]/tbody[1]/tr[@class=&quot;ui-autocomplete-item ui-autocomplete-row ui-widget-content ui-corner-all ui-state-highlight&quot;]/td[2]</value>
      <webElementGuid>fcdfb53b-7afc-4bbc-b089-c4f2effdee44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='InvoiceForm:clinician_panel']/table/tbody/tr[7]/td[2]</value>
      <webElementGuid>5a6a7f84-f947-4e6a-9d9b-c33c578e3f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIDAL ALSKAIF (C) MED'])[1]/following::td[4]</value>
      <webElementGuid>e1094fbc-86ee-44a1-a432-d359c21adf79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAL PRACTICE'])[3]/following::td[6]</value>
      <webElementGuid>adcc83ad-9d7a-430f-8137-6a8d9ddd05e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAL PRACTICE'])[4]/preceding::td[1]</value>
      <webElementGuid>e277f1e0-7591-4a8f-b7b8-e557d0eec4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAL PRACTICE'])[5]/preceding::td[2]</value>
      <webElementGuid>6cb4be65-305d-4ba8-bb78-93a15139d8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/table/tbody/tr[7]/td[2]</value>
      <webElementGuid>3d2bb7db-1e84-4553-a3c5-f23b5352fa75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'AMAL  (R) ELSAID' or . = 'AMAL  (R) ELSAID')]</value>
      <webElementGuid>6e957245-e7dc-499c-82b6-8532888423b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
