<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Telemedicine Assessment  for diagnosis  _320e5d</name>
   <tag></tag>
   <elementGuidId>9211757f-e436-4e75-9d2b-143b4e272f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='AccumedHaadActivityListForm:activityCode_panel']/table/tbody/tr[2]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f34ca564-a6ef-420f-9a88-abad64af6a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Telemedicine Assessment  for diagnosis  treatment  and counselling of a new or established patient by Specialist</value>
      <webElementGuid>e4f566c8-83a4-4622-8a8d-69a6d98b0fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:activityCode_panel&quot;)/table[@class=&quot;ui-autocomplete-items ui-autocomplete-table ui-widget-content ui-widget ui-corner-all ui-helper-reset&quot;]/tbody[1]/tr[@class=&quot;ui-autocomplete-item ui-autocomplete-row ui-widget-content ui-corner-all ui-state-highlight&quot;]/td[2]</value>
      <webElementGuid>abc8b8f5-f2d3-4eab-ac70-72bf8d1666c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='AccumedHaadActivityListForm:activityCode_panel']/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>20a71c6e-99af-4366-b500-b724c574cc8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[4]/following::td[4]</value>
      <webElementGuid>e03b04c6-d138-4640-84ee-17249b707133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[3]/following::td[4]</value>
      <webElementGuid>73ad229c-be48-431e-acbd-8d793bdd21b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='to be billed per seeion'])[1]/preceding::td[8]</value>
      <webElementGuid>24e951b5-e671-45fa-852a-55b572ed3b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test for peritoneal dialysis adequacy'])[1]/preceding::td[10]</value>
      <webElementGuid>dd2b2203-ffee-4a25-a671-235bd2b802c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[7]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>bc501f20-e3d5-46a4-a97e-20baca8ba506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Telemedicine Assessment  for diagnosis  treatment  and counselling of a new or established patient by Specialist' or . = 'Telemedicine Assessment  for diagnosis  treatment  and counselling of a new or established patient by Specialist')]</value>
      <webElementGuid>2780e21d-f715-4541-9bba-581579f4a4c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
