<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>aa35d192-09ac-43d2-b026-dec9b6de7be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedFacilityUserRolesListForm:datalist_paginator_bottom']/span/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ui-paginator-page.ui-state-default.ui-corner-all.ui-state-hover.ui-state-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8eda1b25-16f0-4f11-9c30-bda17ed1e304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-paginator-page ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>0b32a053-302d-416d-97a4-c8bcc4ce4627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9db2fab0-2aff-47d9-b440-d6290708af63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8da0c7c7-b170-4318-a6dc-78059c57e90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Page 2</value>
      <webElementGuid>b25de3ef-107e-4443-ad40-b4b0c929aea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>30e810ed-acdc-477b-80e3-290a5042f5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserRolesListForm:datalist_paginator_bottom&quot;)/span[@class=&quot;ui-paginator-pages&quot;]/a[@class=&quot;ui-paginator-page ui-state-default ui-corner-all ui-state-hover ui-state-focus&quot;]</value>
      <webElementGuid>0c27b4b6-4b50-4991-969d-96a47373bea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedFacilityUserRolesListForm:datalist_paginator_bottom']/span/a[2]</value>
      <webElementGuid>9e701248-5009-42d2-ba99-52b94294480f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>96285d0a-1dde-4124-b101-41abe2ded628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P'])[1]/following::a[2]</value>
      <webElementGuid>4f648792-a519-4639-a85b-97cf0aa4eade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::a[3]</value>
      <webElementGuid>984d463d-8724-4dad-89a3-18764b341b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[1]/preceding::a[1]</value>
      <webElementGuid>ccb9fa30-af29-49ee-b4f1-a04d08a2cb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/preceding::a[2]</value>
      <webElementGuid>05a83766-6706-41b9-bcb0-9b5ca04c98a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>d940d00e-72ab-43d7-af50-d6d53c810f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[25]</value>
      <webElementGuid>12de05b3-a63c-4f3d-9a5e-5d0ea6540dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a[2]</value>
      <webElementGuid>dd431f89-34f5-4ee3-8da6-c9bb85033c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '2' or . = '2')]</value>
      <webElementGuid>326dfd2f-15fb-499f-9b08-af51d01e4f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
