<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ConfirmationAre you sureYesNo</name>
   <tag></tag>
   <elementGuidId>9a05d1ff-668d-4fd1-9ac8-2b10cebb2e70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedFacilityUserRolesListForm:j_idt162']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a6608fc0-fab0-4c75-9195-2b87845a651d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedFacilityUserRolesListForm:j_idt162</value>
      <webElementGuid>a5cffcca-b997-459b-b612-a2ae23b0cdd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-confirm-dialog ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-hidden-container</value>
      <webElementGuid>13698311-e2e8-4cc6-bfcd-9a1358ddc49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>86757e17-959d-471b-bace-ca429c69f76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>AccumedFacilityUserRolesListForm:j_idt162_title</value>
      <webElementGuid>5f3f748f-d58c-4014-8c8b-3906cfadff46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7edfa383-5b0c-4a2f-a89d-1207e293e594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>caa62957-2059-478a-a6e8-e66a248d7509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ConfirmationAre you sure?YesNo</value>
      <webElementGuid>8f13bb01-a745-4dc3-b8e3-cfd1d4e2ea5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserRolesListForm:j_idt162&quot;)</value>
      <webElementGuid>95806ff4-3961-42e9-9332-22d32fa17628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='AccumedFacilityUserRolesListForm:j_idt162']</value>
      <webElementGuid>a9c571db-f067-402d-8c9d-a6a403c95745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows Per Page'])[1]/following::div[4]</value>
      <webElementGuid>359c453e-c976-436c-b3f3-bd12c567e9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::div[4]</value>
      <webElementGuid>fa708f9b-086b-4928-ae4d-09a263a1c146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]</value>
      <webElementGuid>c7075c5b-4ad4-44ac-b9aa-dcf4bb96c27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'AccumedFacilityUserRolesListForm:j_idt162' and (text() = 'ConfirmationAre you sure?YesNo' or . = 'ConfirmationAre you sure?YesNo')]</value>
      <webElementGuid>28821c97-141a-4d53-98dd-b96e93b1cc3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
