<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Claim Submission</name>
   <tag></tag>
   <elementGuidId>2e4d17bd-39fe-4ccf-a54b-95b77088e9ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedFacilityUserRolesCreateForm:pickList']/div/ul/li[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ui-picklist-item.ui-corner-all.ui-sortable-handle.ui-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c8c335c9-6bdb-47f5-882f-a70f793422a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-picklist-item ui-corner-all ui-sortable-handle ui-state-hover</value>
      <webElementGuid>7bf49ee6-770e-4aa6-bf09-a98b8b2fe128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-value</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>2dadf4a6-e59c-4630-91f7-aecfb647bb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-label</name>
      <type>Main</type>
      <value>Claim Submission</value>
      <webElementGuid>4b0c7aa9-659f-4d43-a36f-e5ddd96cbeb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>1ef026aa-9643-440b-bd25-56609bf7b92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Claim Submission</value>
      <webElementGuid>4ef72aa9-9780-47d3-86ee-f59a7c0e3e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserRolesCreateForm:pickList&quot;)/div[@class=&quot;ui-picklist-list-wrapper&quot;]/ul[@class=&quot;ui-widget-content ui-picklist-list ui-picklist-source ui-corner-bottom ui-sortable&quot;]/li[@class=&quot;ui-picklist-item ui-corner-all ui-sortable-handle ui-state-hover&quot;]</value>
      <webElementGuid>cc239a2a-850c-4494-967d-c9e0cd2a45a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedFacilityUserRolesCreateForm:pickList']/div/ul/li[5]</value>
      <webElementGuid>b3b10212-3246-420b-9d6a-9ca9c6335276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Eligibility'])[2]/following::li[1]</value>
      <webElementGuid>8efa705f-0c97-43f5-b427-767c849c997c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch Submission'])[2]/following::li[2]</value>
      <webElementGuid>04d908c9-9fa6-43ac-a865-698fb05373d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinicians Management'])[1]/preceding::li[1]</value>
      <webElementGuid>5f24085f-9750-47b5-9129-be67642a1cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Codes Mapping'])[2]/preceding::li[2]</value>
      <webElementGuid>6d2eb6aa-2992-4982-accd-638312658472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[5]</value>
      <webElementGuid>19515f50-659f-4aac-8dfa-e9b4c316173e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Claim Submission' or . = 'Claim Submission')]</value>
      <webElementGuid>8e2fd090-5a2b-4a7c-9d76-a0ff8591805d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
