<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Male</name>
   <tag></tag>
   <elementGuidId>99ba8004-4694-4ae6-8b9a-e16be031d410</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='AccumedCliniciansCreateForm:gender_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c9e846cd-3ca7-47ea-a9b5-1c2291daeee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>b8f047fe-9529-4485-abdc-c28244b6c52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>61f05724-6850-4a4e-a572-1c9a3d182862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f7dd37aa-fb22-4aa4-b943-628730528b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e46eb8ba-c09a-4208-8681-e9b39c2b4ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedCliniciansCreateForm:gender_1</value>
      <webElementGuid>f72d2a3b-bb0e-46a3-824d-93f1185b7ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>f9f09c72-86c8-4738-a493-784486b7b2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedCliniciansCreateForm:gender_1&quot;)</value>
      <webElementGuid>6e48bf32-9e2a-4354-b18e-1acd88bcc9c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='AccumedCliniciansCreateForm:gender_1']</value>
      <webElementGuid>2529dd8b-d8b0-424e-91f6-843e624fc5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='AccumedCliniciansCreateForm:gender_items']/li[2]</value>
      <webElementGuid>e1365711-e3be-46f2-b9ed-b6bea43e4832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select One...'])[5]/following::li[1]</value>
      <webElementGuid>6e4672c6-4e39-4b8a-9795-0c665fe78eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'AccumedCliniciansCreateForm:gender_1', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>e9acb5ef-f789-451c-b109-8f745a3f920e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[2]/preceding::li[1]</value>
      <webElementGuid>5c0dc6ce-d0e1-434a-8ac4-7d26db581932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select One...'])[6]/preceding::li[2]</value>
      <webElementGuid>cb29dc0d-8f4a-4634-b676-89f5b38725ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/div/ul/li[2]</value>
      <webElementGuid>1e40a092-29ba-475f-97f9-29c5e2a7f540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'AccumedCliniciansCreateForm:gender_1' and (text() = 'Male' or . = 'Male')]</value>
      <webElementGuid>ac3be18c-9c12-4dea-b373-188145f181fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
