<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Profession_ui-chkbox-icon ui-icon ui-i_543df7</name>
   <tag></tag>
   <elementGuidId>df321ed3-4e7e-4889-b25c-8ab92c6f5f06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='AccumedClinicianProfessionsCreateForm:checkboxDT_data']/tr/td/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default.ui-state-hover > span.ui-chkbox-icon.ui-icon.ui-icon-blank.ui-c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3b3fbc4a-a5db-40d5-8a9c-c7b3ea71356e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-chkbox-icon ui-icon ui-icon-blank ui-c</value>
      <webElementGuid>f504e46b-02ad-4983-ae49-e6feccab0eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedClinicianProfessionsCreateForm:checkboxDT_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even ui-datatable-selectable ui-state-hover&quot;]/td[@class=&quot;ui-selection-column&quot;]/div[@class=&quot;ui-chkbox ui-widget&quot;]/div[@class=&quot;ui-chkbox-box ui-widget ui-corner-all ui-state-default ui-state-hover&quot;]/span[@class=&quot;ui-chkbox-icon ui-icon ui-icon-blank ui-c&quot;]</value>
      <webElementGuid>593eee84-8e09-4f20-833e-1eb8853855d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='AccumedClinicianProfessionsCreateForm:checkboxDT_data']/tr/td/div/div[2]/span</value>
      <webElementGuid>f3f9f091-267d-4da3-9cd2-22a846963c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div/div[2]/span</value>
      <webElementGuid>bd115b1d-ca79-43ca-bc84-7fc8b148c120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
