<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Home Care_ui-chkbox-icon ui-icon ui-ic_c29905</name>
   <tag></tag>
   <elementGuidId>bd49c7c3-c77e-4c8a-abc3-eea237ffe581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedCliniciansCreateForm:homeCare']/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-chkbox-icon.ui-icon.ui-icon-blank.ui-c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a0b3c612-941c-4b3e-a0b4-f262b072661a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-chkbox-icon ui-icon ui-icon-blank ui-c</value>
      <webElementGuid>b8cee6be-b86c-4bd7-8b19-05337fd7ca42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedCliniciansCreateForm:homeCare&quot;)/div[@class=&quot;ui-chkbox-box ui-widget ui-corner-all ui-state-default ui-state-hover&quot;]/span[@class=&quot;ui-chkbox-icon ui-icon ui-icon-blank ui-c&quot;]</value>
      <webElementGuid>c94eb711-8fcf-4926-bfca-a1917b10e552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedCliniciansCreateForm:homeCare']/div[2]/span</value>
      <webElementGuid>8efc1deb-a7de-4096-9cfe-6e2010d95d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div[2]/span</value>
      <webElementGuid>a003dbe4-dd16-4005-bb8a-86d94d1e87ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
