<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Clinical Pathology</name>
   <tag></tag>
   <elementGuidId>1fc88c9b-9d55-4b87-996c-2ead54b3ce2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='AccumedClinicianProfessionsCreateForm:checkboxDT_data']/tr[5]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a6126057-d9e3-45d5-b05e-138a476a16f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>c8924b15-922a-4f25-8b0f-28009353d881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clinical Pathology</value>
      <webElementGuid>25526226-c58c-478d-b587-931aa13f5f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedClinicianProfessionsCreateForm:checkboxDT_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even ui-datatable-selectable&quot;]/td[2]</value>
      <webElementGuid>0053ece4-2e0e-48bf-9758-0776c1fdabfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='AccumedClinicianProfessionsCreateForm:checkboxDT_data']/tr[5]/td[2]</value>
      <webElementGuid>8b2ce715-ebb9-4375-ab18-6326f4a3d411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anesthesia'])[2]/following::td[2]</value>
      <webElementGuid>af25371c-eb7e-4f6a-af9c-3f0cf573a2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anesthesia'])[1]/following::td[4]</value>
      <webElementGuid>233de9e2-6783-427a-9fa9-6a3cbed85ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinical Pathology'])[2]/preceding::td[2]</value>
      <webElementGuid>83a214e7-5648-4789-bf0c-8ae7c367600e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dentistry'])[1]/preceding::td[4]</value>
      <webElementGuid>a5bc2647-2a01-419f-bcd3-e4fbf12b54ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clinical Pathology']/parent::*</value>
      <webElementGuid>d9695a55-695e-4b87-a55c-15cb3e720097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]/table/tbody/tr[5]/td[2]</value>
      <webElementGuid>7466b6fc-8e2d-4bbc-9564-efdbe36a1c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Clinical Pathology' or . = 'Clinical Pathology')]</value>
      <webElementGuid>bc91efa3-9b05-42dc-b928-4243edc7f130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
