<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_National ID_AccumedPatientCreateForme_a5ef9f</name>
   <tag></tag>
   <elementGuidId>e9e18356-03f7-4fe7-bb93-a77c847f6f92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedPatientCreateForm:emiratesId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf28d106-8d56-4147-ac23-38c4e5b4b517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientCreateForm:emiratesId</value>
      <webElementGuid>e00ab19b-c464-4c6a-9c73-47c1d7eefe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedPatientCreateForm:emiratesId</value>
      <webElementGuid>e46c9666-2a75-44e5-a2ed-0fb4ebc7f224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>606610ab-7903-4d58-90e0-f1aeed456ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedPatientCreateForm:emiratesId&quot;,e:&quot;keyup&quot;,p:&quot;AccumedPatientCreateForm:emiratesId&quot;,u:&quot;AccumedPatientCreateForm:msgLastname AccumedPatientCreateForm:createButton&quot;});</value>
      <webElementGuid>2e883727-405f-46ff-be1b-af1df4b6e010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>5d99b4a7-ed39-4a6e-aa30-843d25bf5b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c8b00928-0fa2-4029-b7df-f82acdf00a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ddb55cd-bb9b-4d28-a6cd-a0d42358bd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>27b0d013-d264-425d-867b-e40312c2f246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientCreateForm:emiratesId&quot;)</value>
      <webElementGuid>bc2bcb4e-e888-4f93-b156-7bc12baf3653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedPatientCreateForm:emiratesId']</value>
      <webElementGuid>4d3a5e77-4d3b-4776-b690-774ecf8e75d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AccumedPatientCreateForm:j_idt289']/tbody/tr/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>adf93fb0-28e6-4490-8fc9-c492a490c727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>eac33fb1-b53f-4b0e-b16f-dc3d7c806f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedPatientCreateForm:emiratesId' and @name = 'AccumedPatientCreateForm:emiratesId' and @type = 'text']</value>
      <webElementGuid>8873c069-9170-4656-9e93-25ce34a8cf1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
