<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Print</name>
   <tag></tag>
   <elementGuidId>85d373ff-3009-469b-90cd-b738edb50ede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='collectionForm:patientAdvanceTBL:0:printInvoice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b0169e9a-8bad-44fb-aab1-f9b6caffff8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collectionForm:patientAdvanceTBL:0:printInvoice</value>
      <webElementGuid>93388820-1757-43ab-b986-623af5a1f08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d1626665-ee0f-493c-b0e0-e322c2df5452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget</value>
      <webElementGuid>b0623e44-700e-46cc-8475-6d3e71fa856c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;collectionForm:patientAdvanceTBL:0:printInvoice&quot;,u:&quot;collectionForm&quot;,onst:function(cfg){startAjaxLoader('GENERATING REPORT IN PROGRESS...');;},onco:function(xhr,status,args){ printJS({printable: document.getElementById('collectionForm:reportRoot').innerHTML, type: 'pdf', base64: true} ) ;endAjaxLoader();;}});return false;</value>
      <webElementGuid>ab6021d4-19a1-4379-a294-0d1329c8ac3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Print</value>
      <webElementGuid>cc0eb028-66b8-456b-bd72-5d052e1a4264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collectionForm:patientAdvanceTBL:0:printInvoice&quot;)</value>
      <webElementGuid>653094c0-80d9-4600-b661-372889ea78bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='collectionForm:patientAdvanceTBL:0:printInvoice']</value>
      <webElementGuid>f54c53de-2d39-40a8-9f93-cc8e10eb17a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='collectionForm:patientAdvanceTBL_data']/tr/td[11]/a[2]</value>
      <webElementGuid>5b8bb63a-39a0-4f9d-858f-ff279e967749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Print')]</value>
      <webElementGuid>1e62e951-077d-42bd-adc5-5dcc1164a612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='administrator /'])[1]/following::a[2]</value>
      <webElementGuid>da370250-2d7e-4a65-86a8-b86f148bf1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASH'])[1]/following::a[2]</value>
      <webElementGuid>6253646f-6a2f-49da-a124-57dae6d1df9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PATIENT jjjdd PATIENT'])[1]/preceding::a[1]</value>
      <webElementGuid>41f8b3f8-1a7a-4665-9f80-c561fdcfa8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AFGHANISTAN'])[2]/preceding::a[1]</value>
      <webElementGuid>115cf4c5-b190-4f31-9c52-e6e8cba457a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Print']/parent::*</value>
      <webElementGuid>6a7bbc62-af82-4b4d-aa3d-7652ad5a1df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[24]</value>
      <webElementGuid>88026a8b-23ae-4475-972b-6717319d31c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>6abb5a04-fe30-4b9c-a5c2-f793115910a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'collectionForm:patientAdvanceTBL:0:printInvoice' and @href = '#' and (text() = 'Print' or . = 'Print')]</value>
      <webElementGuid>edcb2fd7-3ca0-4b47-8b7f-ea7adf843bd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
