<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_ADC1</name>
   <tag></tag>
   <elementGuidId>c9389f66-744c-4dbc-9939-342d36e7335e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=&quot;advanceCollectionDlgForm:j_idt268&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>56e23a4c-adad-41a6-8fa4-235982405068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1669278181965</value>
      <webElementGuid>4c4e274a-43eb-4fa1-94f4-ca4d03040993</webElementGuid>
   </webElementProperties>
</WebElementEntity>
