<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount Received_advanceCollectionDlgF_e586c6</name>
   <tag></tag>
   <elementGuidId>4c1a8f0a-f16b-4208-acbe-041f59828aab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='advanceCollectionDlgForm:paymentForm:0:Amount_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45d90ca2-9db7-4274-8858-968f0a3cfe47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advanceCollectionDlgForm:paymentForm:0:Amount_input</value>
      <webElementGuid>dc8c2f5c-604d-4704-8fe8-5c9996de0a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>advanceCollectionDlgForm:paymentForm:0:Amount_input</value>
      <webElementGuid>74f4a807-ee2d-4864-9c13-2df29487832b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dcfb4a16-260d-4463-9a8f-2cc9e291dea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>42ccade5-d267-4f11-b53e-ad16897b37e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;advanceCollectionDlgForm:paymentForm:0:Amount&quot;,e:&quot;valueChange&quot;,p:&quot;advanceCollectionDlgForm:paymentForm:0:Amount&quot;,u:&quot;advanceCollectionDlgForm:paymentForm&quot;});</value>
      <webElementGuid>2660c9fe-e5ec-47ba-9bb5-1b91c16b0e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>e81b0d3f-73a4-45d4-89f4-1693efd6f069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>824e158d-9cc3-40fc-972e-d83c66abff88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>eacb1cbc-60ea-45a6-bbf5-6e6826440242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6b7bb232-493d-406e-a115-9eab6322feff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dba09a5b-83db-4c87-8ba3-a4f54722a445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advanceCollectionDlgForm:paymentForm:0:Amount_input&quot;)</value>
      <webElementGuid>30c72b29-1ebe-424d-ac51-4062703dc21d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='advanceCollectionDlgForm:paymentForm:0:Amount_input']</value>
      <webElementGuid>01e39afd-3dcf-4ea1-8b44-fa9c6c50c5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='advanceCollectionDlgForm:paymentForm:0:Amount']/input</value>
      <webElementGuid>f36ca3c3-ca23-497a-af8d-bb581f1e63d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/span/input</value>
      <webElementGuid>c4c6fa3f-fe11-4d85-bac6-77bf7e9546d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'advanceCollectionDlgForm:paymentForm:0:Amount_input' and @name = 'advanceCollectionDlgForm:paymentForm:0:Amount_input' and @type = 'text']</value>
      <webElementGuid>66d3e5b1-e551-408b-a300-c63a1b48d0c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
