<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Patient_advanceCollectionDlgFo_160f63</name>
   <tag></tag>
   <elementGuidId>5efa5c12-7947-4609-abba-4f30abe69ce7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='advanceCollectionDlgForm:patient_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79e630c1-5759-4023-aa4a-cb380b0687dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advanceCollectionDlgForm:patient_input</value>
      <webElementGuid>7960e50c-fab4-4321-bc93-bef35d1f2f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>advanceCollectionDlgForm:patient_input</value>
      <webElementGuid>0f6345b1-5a3c-4c98-a28c-cb52695555fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d5305f9-fdd1-4faa-9bb7-04d24a5494c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input ui-inputfield ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>00a062fd-028c-4b40-92a8-aff2daa651e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>99b185d1-63ba-48fa-8c86-ea1061353701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by Mrn ,National ID, Name and Phone Number.</value>
      <webElementGuid>00b98808-9e16-401e-b9de-fc9aacf71c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>f3d241c2-5ae0-4f97-89ab-9a4b1f388bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search by Mrn ,National ID, Name and Phone Number.</value>
      <webElementGuid>c9001ef5-fc99-4441-9a0d-3ed4463052e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c939d16e-6234-4b6d-839c-2228079e9f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5590682f-edad-4ae5-a04a-76ed0ece85e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2e471e3a-eefc-408f-bef0-0d8ad73a395f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>d4a13653-12fd-4cde-9dd5-e7e0f513ac8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advanceCollectionDlgForm:patient_input&quot;)</value>
      <webElementGuid>b52b343f-a0ee-4d26-94c7-d6a1093501d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='advanceCollectionDlgForm:patient_input']</value>
      <webElementGuid>21e1ccd7-0d92-491d-aade-5dbb366fea17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='advanceCollectionDlgForm:patient']/input</value>
      <webElementGuid>4ea919d8-7584-42d5-9b60-921ee6b8b40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/table/tbody/tr/td/table/tbody/tr/td/span/input</value>
      <webElementGuid>590a9513-e30b-4478-b156-d69081c747cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'advanceCollectionDlgForm:patient_input' and @name = 'advanceCollectionDlgForm:patient_input' and @type = 'text' and @placeholder = 'Search by Mrn ,National ID, Name and Phone Number.' and @title = 'Search by Mrn ,National ID, Name and Phone Number.']</value>
      <webElementGuid>b8442fc2-1732-408f-8812-88c261402646</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
