<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_yatyaha hussqm kiarnh</name>
   <tag></tag>
   <elementGuidId>d8aec626-b0cf-4c9f-80c4-e17d82924d7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='advanceCollectionDlgForm:patient_panel']/table/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8f9b7e07-3b0f-467d-b618-1a28a84031fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> yatyaha hussqm kiarnh </value>
      <webElementGuid>c659b093-3bd2-4cf6-99d3-ebd5102761d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advanceCollectionDlgForm:patient_panel&quot;)/table[@class=&quot;ui-autocomplete-items ui-autocomplete-table ui-widget-content ui-widget ui-corner-all ui-helper-reset&quot;]/tbody[1]/tr[@class=&quot;ui-autocomplete-item ui-autocomplete-row ui-widget-content ui-corner-all ui-state-highlight&quot;]/td[2]</value>
      <webElementGuid>bee49f63-1e04-4d9b-a817-59e455d9c735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='advanceCollectionDlgForm:patient_panel']/table/tbody/tr/td[2]</value>
      <webElementGuid>6edcc8d1-2d05-4ecc-b1ca-32d80e2d14bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[1]/following::td[2]</value>
      <webElementGuid>637d2597-7b2e-49c5-afc7-2339d6dae62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MRN'])[3]/following::td[2]</value>
      <webElementGuid>6ab02212-89c8-4b2a-a769-b6e1f6221f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mrn-00009'])[1]/preceding::td[1]</value>
      <webElementGuid>51946eb1-874e-4267-8b13-55488fee30f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='yatyaha hussqm kiarnh']/parent::*</value>
      <webElementGuid>90134001-9cc5-4c44-adf4-9f87d3fe3a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>6e631403-676b-4911-b2c3-befe4256bc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' yatyaha hussqm kiarnh ' or . = ' yatyaha hussqm kiarnh ')]</value>
      <webElementGuid>9bc19982-4d74-48ec-8cc0-3e9aab4ffa17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
