<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PaymentAmount_paymentFormpayment0Amount_input</name>
   <tag></tag>
   <elementGuidId>fddff316-698f-41ec-b832-5d56e4dbd6c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentForm:payment:0:Amount_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cf9da7d-ea5e-48e0-8185-6a5857f96fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentForm:payment:0:Amount_input</value>
      <webElementGuid>6c57a1e4-bc67-4b0a-8bb0-888ba967e55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentForm:payment:0:Amount_input</value>
      <webElementGuid>9df1e1e3-f672-4ebe-981f-bda819bcc02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22653928-1822-49a5-acb0-acc95890aab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>7b541839-5e08-45e3-9794-5ec8c85a2b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;paymentForm:payment:0:Amount&quot;,e:&quot;keyup&quot;,p:&quot;paymentForm:payment:0:Amount&quot;,u:&quot;@none&quot;});</value>
      <webElementGuid>09e050b4-f3f2-4c9f-86b0-fe933c517274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>79e39c6d-e6b3-4997-9ddd-fab9e1d08efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus</value>
      <webElementGuid>5aa1c31d-8b80-4e1c-aa99-363b8341c550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>9f658641-b3c7-4107-977d-7b15adfdf99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>321b0032-0ec6-4520-8d4a-1f48d804415f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>28f6c5b7-341d-4f13-ac28-cc8367b7f3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentForm:payment:0:Amount_input&quot;)</value>
      <webElementGuid>d6dcee1c-fa58-4b31-97b0-62b2f5695d19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentForm:payment:0:Amount_input']</value>
      <webElementGuid>08a123bf-9286-4175-91c2-a6e7a238f79e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='paymentForm:payment:0:Amount']/input</value>
      <webElementGuid>31c257d1-fd0b-484b-b8a3-6f9469584d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/span/input</value>
      <webElementGuid>167761cf-fd9d-42a8-bb81-141165b0f307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'paymentForm:payment:0:Amount_input' and @name = 'paymentForm:payment:0:Amount_input' and @type = 'text']</value>
      <webElementGuid>f951621d-d7fe-4cec-b0c0-3c702d9f0538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
