<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PARACETAMOL_AccumedHaadActivityListFo_f3f533</name>
   <tag></tag>
   <elementGuidId>f7a1f79f-594c-4b67-a49d-b4e27dd9ee40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedHaadActivityListForm:datalist:0:j_idt902_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfb50990-1864-4d6b-9bcc-64e1fab4cf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:datalist:0:j_idt902_input</value>
      <webElementGuid>581efa99-2b31-4f61-9b88-fca1e865213b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:datalist:0:j_idt902_input</value>
      <webElementGuid>1a13021e-e239-4eba-afa8-7c296809d93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce03332f-4ce3-4430-b016-b0fd6127f7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10.0</value>
      <webElementGuid>58bef5d8-49c6-4900-9bca-70275b47d520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8a416b04-f44b-4a76-b216-523fc000e1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedHaadActivityListForm:datalist:0:j_idt902&quot;,e:&quot;valueChange&quot;,p:&quot;AccumedHaadActivityListForm:datalist:0:j_idt902&quot;,u:&quot;paymentForm actionsButtonsForm AccumedHaadActivityListForm:datalist&quot;,onco:function(xhr,status,args){PF('dataTableActivity').filter();}});</value>
      <webElementGuid>63d11817-fb62-4e9d-9fe2-1475b65d6f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>4956a1ed-d67a-4dfb-8e05-272118ea9067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>76db98b5-ba55-4d19-8e93-ee84c50afd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>12fb2525-0cd0-416e-a81a-cd1b8b4e741b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0c958a25-e3b9-4b68-99b6-492cc1343c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>03e9088f-42ad-4f44-9d1a-45bc4b86cb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:datalist:0:j_idt902_input&quot;)</value>
      <webElementGuid>f052283a-a7a1-42b5-ade1-500ea28b10b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedHaadActivityListForm:datalist:0:j_idt902_input']</value>
      <webElementGuid>f745bccc-4751-4f3a-a7c6-c1217439b9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='AccumedHaadActivityListForm:datalist:0:j_idt902']/input</value>
      <webElementGuid>43f3c353-6664-40b5-8532-7b8bba52ece2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/span/input</value>
      <webElementGuid>48170b4b-1240-487c-b4d0-419149d7155a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedHaadActivityListForm:datalist:0:j_idt902_input' and @name = 'AccumedHaadActivityListForm:datalist:0:j_idt902_input' and @type = 'text']</value>
      <webElementGuid>3bc3bfc2-7ed0-4bb4-ae25-8d96c1354ac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
