<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>43ad1964-22b4-49f7-9f5f-65594b219d5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='phWLForm:j_idt183']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7cfc2842-dbd0-4c49-b10c-68e592576d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phWLForm:j_idt183</value>
      <webElementGuid>6a44b4c5-068c-422c-aa58-51fd8cac8211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phWLForm:j_idt183</value>
      <webElementGuid>788b3e20-1936-439e-bba3-7d10b7034a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-focus ui-state-hover</value>
      <webElementGuid>db494d51-3862-482a-aa49-7267c79c1e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;phWLForm:j_idt183&quot;,u:&quot;phWLForm:phWLTbl&quot;,onst:function(cfg){PF('standardAjaxStatusDialog').show();;},onco:function(xhr,status,args){PF('standardAjaxStatusDialog').hide();;}});return false;</value>
      <webElementGuid>c4e64b10-8316-4d17-a830-8d64e04db4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>89087baf-b1bb-4db7-bb35-95cd4d0239f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a322ace7-5ee6-4b72-87eb-9f2d3dba87a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f9433a3a-88fe-41b8-b3e8-774f10918fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>19ac2b66-f9c2-4d2f-86f0-e83a18f61b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phWLForm:j_idt183&quot;)</value>
      <webElementGuid>2c5cf921-2b0a-4291-9f96-9102a5126ccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='phWLForm:j_idt183']</value>
      <webElementGuid>c72d1cd6-085e-473e-b7f7-a93a097359a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='phWLForm']/table/tbody/tr/td[2]/button</value>
      <webElementGuid>d06291c4-bc71-4ba7-b358-9eaace01b78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved /Partially / Rejected'])[1]/following::button[1]</value>
      <webElementGuid>8cf82ff5-a6d2-4337-b57a-4644ac98f962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Query'])[1]/following::button[1]</value>
      <webElementGuid>9c10ee6d-fbe1-49bb-8e00-5d00cf8446cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient'])[2]/preceding::button[1]</value>
      <webElementGuid>1d38c9bf-a11b-4edc-a25d-45bf6e812cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/table/tbody/tr/td[2]/button</value>
      <webElementGuid>d1ac2230-ac03-472d-97a4-4bc02c5b8151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'phWLForm:j_idt183' and @name = 'phWLForm:j_idt183' and @type = 'submit' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>3b2bd526-5a95-4413-a441-ef16a52d66bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
