<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Approval Required_ui-selectonemenu-trig_b2d223</name>
   <tag></tag>
   <elementGuidId>7719373e-1d2a-4c58-8262-3f061e85300a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedHaadActivityListForm:datalist:j_idt465']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-selectonemenu-trigger.ui-state-default.ui-corner-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>937d8174-ad9d-4a1f-804b-516ef87f171f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-trigger ui-state-default ui-corner-right</value>
      <webElementGuid>3620f7e9-ecd1-4f9d-ad90-19e24f6ea8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:datalist:j_idt465&quot;)/div[@class=&quot;ui-selectonemenu-trigger ui-state-default ui-corner-right&quot;]</value>
      <webElementGuid>3a01edac-c131-4249-bacc-e1f0f2dc21d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedHaadActivityListForm:datalist:j_idt465']/div[3]</value>
      <webElementGuid>3e50d34b-e93f-49df-b2b1-405f787d2fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Required'])[2]/following::div[1]</value>
      <webElementGuid>683fb52e-d6af-41a7-b01c-98e00ad214c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::div[1]</value>
      <webElementGuid>9c922f37-25d5-410d-b12d-8beb4b992767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes, If any'])[1]/preceding::div[1]</value>
      <webElementGuid>fd3599a4-74c3-42fd-afb6-ff2e2615b5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[3]</value>
      <webElementGuid>ca8908ac-b040-432a-917a-9261f963b3bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
