<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approval Code_AccumedHaadActivityList_25d573</name>
   <tag></tag>
   <elementGuidId>cdb8557f-0a18-415e-91af-a9ae9c8da808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedHaadActivityListForm:datalist:4:valorTotalItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8cef88b-fdff-405a-a468-2c60993ebe81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:datalist:4:valorTotalItem</value>
      <webElementGuid>54f74941-5598-4880-938d-6bee65fc985b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:datalist:4:valorTotalItem</value>
      <webElementGuid>f7844f73-26e0-4d6f-9c0e-606817dcbf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1f4475b-3558-4152-877c-bbc0b7c6d2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedHaadActivityListForm:datalist:4:valorTotalItem&quot;,e:&quot;valueChange&quot;,p:&quot;AccumedHaadActivityListForm:datalist:4:valorTotalItem&quot;,u:&quot;AccumedHaadActivityListForm:datalist&quot;});</value>
      <webElementGuid>476b747b-3527-447f-863c-567d2d71d77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>a7d9414b-649e-4a32-b3bc-73ac42a0cd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>63557202-0ee2-4374-9b46-a9c0e54f3270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>40df1f5f-d1d3-4df0-8176-76ec2ec77265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>55c11d07-016d-47dd-93c3-562cd7e7315b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:datalist:4:valorTotalItem&quot;)</value>
      <webElementGuid>5ff14670-4850-4ba7-99fb-f32e1bd86294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedHaadActivityListForm:datalist:4:valorTotalItem']</value>
      <webElementGuid>cbc87253-84f3-4274-a54c-17ad2a3405ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='AccumedHaadActivityListForm:datalist_data']/tr[5]/td[8]/input</value>
      <webElementGuid>6845a7c4-a9a7-4e0d-a8c3-86efd6f66474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[8]/input</value>
      <webElementGuid>b3766b47-ea9c-4c62-ad62-b86ade7c9f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedHaadActivityListForm:datalist:4:valorTotalItem' and @name = 'AccumedHaadActivityListForm:datalist:4:valorTotalItem' and @type = 'text']</value>
      <webElementGuid>2559b84c-bd21-4b21-aee3-0a06661103ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
