<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approval Code_AccumedHaadActivityListFormdatalist1valorTotalItem</name>
   <tag></tag>
   <elementGuidId>86e220e4-718b-4e2d-94bc-6cc7a01fc18d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedHaadActivityListForm:datalist:1:valorTotalItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edadbef5-08aa-41ab-b604-55b13e289690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:datalist:1:valorTotalItem</value>
      <webElementGuid>4515f0a0-c63f-4261-930a-39caa0360a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:datalist:1:valorTotalItem</value>
      <webElementGuid>88cb9b17-c368-443f-ab99-e8a3aca5e46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ae9b7dd-2963-400c-984e-6aae7b6a09f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedHaadActivityListForm:datalist:1:valorTotalItem&quot;,e:&quot;valueChange&quot;,p:&quot;AccumedHaadActivityListForm:datalist:1:valorTotalItem&quot;,u:&quot;AccumedHaadActivityListForm:datalist&quot;});</value>
      <webElementGuid>351b4738-4149-4afe-98db-a78f6bf6d02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus</value>
      <webElementGuid>bc29641d-d96a-46db-8c9e-52da3953f822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e9e42617-be51-4c09-8403-8b87af0f0fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>309a3e3c-87f9-49f0-8af9-f8bdef2f84ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>162ed7de-5a1c-46ae-a739-6d7a7c81e06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:datalist:1:valorTotalItem&quot;)</value>
      <webElementGuid>6ab12fa8-215a-4b3f-ac73-15a4ebdd8d4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedHaadActivityListForm:datalist:1:valorTotalItem']</value>
      <webElementGuid>21eda93e-24ca-4c98-bb1a-13c1050ff003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='AccumedHaadActivityListForm:datalist_data']/tr[2]/td[8]/input</value>
      <webElementGuid>e73087fd-8d17-40ef-a8c6-7798b485e239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/input</value>
      <webElementGuid>d79bfe04-2fa7-449e-ab40-88e34c11d66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedHaadActivityListForm:datalist:1:valorTotalItem' and @name = 'AccumedHaadActivityListForm:datalist:1:valorTotalItem' and @type = 'text']</value>
      <webElementGuid>90db0e42-06d3-4b47-93b6-260a1d013d33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
