<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Approval Required</name>
   <tag></tag>
   <elementGuidId>8331183a-4c1f-4ee2-91c4-fafb7ff249e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='AccumedHaadActivityListForm:datalist:j_idt465_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2ff2b521-cad5-4500-92b9-b82a9662d7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:datalist:j_idt465_label</value>
      <webElementGuid>3d6abdd7-0f00-42bd-8502-215aacc6703d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>dd813048-fc6e-464b-a3a6-3b3e64e91f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approval Required</value>
      <webElementGuid>367969d5-8efd-4090-8d71-884b0b78a06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:datalist:j_idt465_label&quot;)</value>
      <webElementGuid>cd26d27e-7e95-48a9-9a88-21a2dfd51d79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='AccumedHaadActivityListForm:datalist:j_idt465_label']</value>
      <webElementGuid>ec94c003-d7d3-42d4-bd37-4c7952e2f45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedHaadActivityListForm:datalist:j_idt465']/label</value>
      <webElementGuid>0b71f0a7-e7cc-4040-97d7-2749e31f1b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Amount'])[1]/following::label[1]</value>
      <webElementGuid>394b6bc0-82a8-4721-8d27-b35891fba3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::label[1]</value>
      <webElementGuid>42a5fa27-720d-4137-985d-29d2b7e37cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes, If any'])[1]/preceding::label[1]</value>
      <webElementGuid>900cccee-b80c-4887-9026-3535b796615f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/label</value>
      <webElementGuid>ffa7f412-7c60-4947-a880-7854a41cc98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'AccumedHaadActivityListForm:datalist:j_idt465_label' and (text() = 'Approval Required' or . = 'Approval Required')]</value>
      <webElementGuid>e780fe70-3566-419f-a176-1e978d53ddfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
