<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PaymentAmount_paymentFormpayment0Amou_c31842</name>
   <tag></tag>
   <elementGuidId>a040bf51-8f10-40d7-9078-cacc2f0048f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentForm:payment:0:Amount_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5fbe260-d1b4-4b08-a41a-d1593d61f9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentForm:payment:0:Amount_input</value>
      <webElementGuid>056f40a2-c8aa-4d35-a4db-e574ee47a747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentForm:payment:0:Amount_input</value>
      <webElementGuid>1b4ca884-a644-4bb4-821c-eb88534732ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18fdfa9f-3edb-4d13-a2e0-1e82af2c00c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>36b29109-8942-45c8-b886-f63bd6ba1df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;paymentForm:payment:0:Amount&quot;,e:&quot;keyup&quot;,p:&quot;paymentForm:payment:0:Amount&quot;,u:&quot;@none&quot;});</value>
      <webElementGuid>d3aa01e7-fc2d-4df3-85f2-807124cdc2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>65be78fe-dd65-47e6-8698-63d7e7d55e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>47df8a4f-250b-4a0b-8fbf-4bf5f1e4b2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ed68e753-1787-46a3-abb6-e62350d50eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>97fd5975-9a17-4b59-a281-bde2765cac0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>40a97903-edd9-4ea9-bc6a-f3b64d0b5746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentForm:payment:0:Amount_input&quot;)</value>
      <webElementGuid>e69150bc-5cfb-4ad4-925a-67792ee9676e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentForm:payment:0:Amount_input']</value>
      <webElementGuid>4f8bdfee-9a16-4969-b2da-99ab9c4842e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='paymentForm:payment:0:Amount']/input</value>
      <webElementGuid>81e4e325-6710-4840-845a-9ef494e79d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/span/input</value>
      <webElementGuid>b76c3d0d-d39a-4e1a-9e8a-8df9bf98384c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'paymentForm:payment:0:Amount_input' and @name = 'paymentForm:payment:0:Amount_input' and @type = 'text']</value>
      <webElementGuid>60f73262-c347-4667-b9c9-3729c7cbd3cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
