<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Net Amount Received_opcol7</name>
   <tag></tag>
   <elementGuidId>7c417780-2b23-4cb0-bb3e-cd8001ebf4a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dl[@id='paymentForm:payment_list']/dt/table/tbody/tr[3]/td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fcc69bf5-6a7b-45fe-8e14-f4c4054cf87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>opcol7</value>
      <webElementGuid>94b2b9fb-a099-40c4-83b0-a263c5d6652e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentForm:payment_list&quot;)/dt[@class=&quot;ui-datalist-item&quot;]/table[1]/tbody[1]/tr[3]/td[@class=&quot;opcol7&quot;]</value>
      <webElementGuid>ba783ff0-c479-4669-bc3c-1f5ed836e404</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dl[@id='paymentForm:payment_list']/dt/table/tbody/tr[3]/td[7]</value>
      <webElementGuid>b0e9c9ca-3fc4-4f74-9fb1-760b5e401670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dt/table/tbody/tr[3]/td[7]</value>
      <webElementGuid>1d53141e-9797-453f-a36f-d9a1a1edfd28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
