<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter by MRN_refundFormdtBillsj_idt179filter</name>
   <tag></tag>
   <elementGuidId>1d2a9218-5927-491d-af78-ac32af5d7802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refundForm:dtBills:j_idt179:filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70cfe9b1-1239-40ca-81c7-765e2c82b149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refundForm:dtBills:j_idt179:filter</value>
      <webElementGuid>2aaebf48-771d-4915-8147-cedc3bae92cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refundForm:dtBills:j_idt179:filter</value>
      <webElementGuid>e28022e9-fb0f-4fa3-b097-cacb57d6b4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-column-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>fe103539-2a0f-4d23-9328-317da09c2137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2aa67476-e44e-4b9a-b7c2-0f8fb9c82e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>refundForm:dtBills:j_idt179:filter_label</value>
      <webElementGuid>123f72cc-55e1-4770-bcd7-ebcc32e51d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>762c49c1-5604-4a95-bf75-071497a944c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7efe645a-c762-4dcf-9f60-5949c39b224c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>760a2fdd-7d8f-4551-8881-ff132685e7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refundForm:dtBills:j_idt179:filter&quot;)</value>
      <webElementGuid>6ead782f-4eaf-498d-8127-b90a36da8f43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refundForm:dtBills:j_idt179:filter']</value>
      <webElementGuid>e9d711af-778c-497c-b7e5-533c7a929cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='refundForm:dtBills:j_idt179']/input</value>
      <webElementGuid>7cabb426-df38-4c2c-adc6-483fe1fb2ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/input</value>
      <webElementGuid>2f6e74a2-72ec-4047-9ebd-aec283a3d2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'refundForm:dtBills:j_idt179:filter' and @name = 'refundForm:dtBills:j_idt179:filter']</value>
      <webElementGuid>ae6e1f87-ffc1-4211-be81-306bbe3388b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
