<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Paid_ui-chkbox-icon ui-icon ui-icon-bl_14296d</name>
   <tag></tag>
   <elementGuidId>924fe766-1b56-4c7f-b8de-fc988c30edcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default.ui-state-hover > span.ui-chkbox-icon.ui-icon.ui-icon-blank.ui-c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='billItemsForm:dtBillItems_data']/tr[3]/td/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c56febe7-fe3f-4ce1-9473-d55ef167dc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-chkbox-icon ui-icon ui-icon-blank ui-c</value>
      <webElementGuid>11bc71a0-340c-4fdb-a206-7be47e2cac1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billItemsForm:dtBillItems_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even ui-datatable-selectable ui-state-hover&quot;]/td[@class=&quot;ui-selection-column textaligncenter&quot;]/div[@class=&quot;ui-chkbox ui-widget&quot;]/div[@class=&quot;ui-chkbox-box ui-widget ui-corner-all ui-state-default ui-state-hover&quot;]/span[@class=&quot;ui-chkbox-icon ui-icon ui-icon-blank ui-c&quot;]</value>
      <webElementGuid>de5b8591-d780-4a78-8ca0-a9615e42f34e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='billItemsForm:dtBillItems_data']/tr[3]/td/div/div[2]/span</value>
      <webElementGuid>309a8969-7f6b-4c6c-acb4-397a28325341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div[2]/span</value>
      <webElementGuid>08f09ccf-5629-4887-87d6-bc2c0b448d34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
