<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Report_ui-icon ui-icon-closethick</name>
   <tag></tag>
   <elementGuidId>d2b3aae2-dead-4a1a-b182-6a1d81c0f37e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ui-dialog-titlebar-icon.ui-dialog-titlebar-close.ui-corner-all.ui-state-hover.ui-state-focus > span.ui-icon.ui-icon-closethick</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='previewReport']/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4bcb6505-0c6f-4b23-ac49-8f4aea0ffb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-icon ui-icon-closethick</value>
      <webElementGuid>06e07a18-95e3-44ab-9af1-138af7eee961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;previewReport&quot;)/div[@class=&quot;ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-corner-top ui-draggable-handle&quot;]/a[@class=&quot;ui-dialog-titlebar-icon ui-dialog-titlebar-close ui-corner-all ui-state-hover ui-state-focus&quot;]/span[@class=&quot;ui-icon ui-icon-closethick&quot;]</value>
      <webElementGuid>68b20318-b5e6-473c-91c9-d5cbab59672b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='previewReport']/div/a/span</value>
      <webElementGuid>6c1db692-e645-4918-9829-dd8178747b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/a/span</value>
      <webElementGuid>09654fc4-2707-451c-a9e5-fd0ff2036679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
