<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Department Wise Revenue Report</name>
   <tag></tag>
   <elementGuidId>723f4bd5-f1d5-4858-92af-75f2c9e596fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='MISReportsForm:j_idt162_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c9a49965-6643-449e-8c88-70b6ed82f7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>9f9280a3-6bca-41db-9c57-560e6a834986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Department Wise Revenue Report</value>
      <webElementGuid>2fd4fcd2-48ec-4ea5-bcbc-e870000c0d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>796fade2-2550-461e-aba2-6246084d711f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a0fbbd26-7b57-438a-9bc2-ea8f6dd04b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MISReportsForm:j_idt162_2</value>
      <webElementGuid>19d75292-108b-41c4-9ca1-92e20102bb38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Department Wise Revenue Report</value>
      <webElementGuid>7c0b5c76-205a-45d8-a5b4-53f5b1ceb914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MISReportsForm:j_idt162_2&quot;)</value>
      <webElementGuid>63840bc0-242c-4331-bbf0-1376c63ee13c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='MISReportsForm:j_idt162_2']</value>
      <webElementGuid>621f4022-0da3-4728-9be1-5e834dcc3bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='MISReportsForm:j_idt162_items']/li[3]</value>
      <webElementGuid>c1cff4bd-bc2c-475d-894c-a555749a3832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department wise Patient count for Service availed'])[2]/following::li[1]</value>
      <webElementGuid>7075253a-2c98-4b27-8b1b-89684d2afe49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly Revenue'])[3]/following::li[2]</value>
      <webElementGuid>3331dd37-6764-40de-bf11-2e8b3308b82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctor wise Patient count and Revenue'])[2]/preceding::li[1]</value>
      <webElementGuid>82bcf4a1-fe63-4b86-b1bb-35024c7307e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctor wise Service item wise detailed revenue'])[2]/preceding::li[2]</value>
      <webElementGuid>b088e2d9-25bf-4fae-82b3-1f51c55d8674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/ul/li[3]</value>
      <webElementGuid>de6d8a85-609d-4504-bdec-20c344352ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'MISReportsForm:j_idt162_2' and (text() = 'Department Wise Revenue Report' or . = 'Department Wise Revenue Report')]</value>
      <webElementGuid>b88625d1-09a8-460b-a8ce-b4d651e433de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
