<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_OP</name>
   <tag></tag>
   <elementGuidId>6a2acfb3-6d73-441c-9276-3e447a01b5fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='MISReportsForm:j_idt212_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>795ce332-cb2c-43c0-ba60-d762a4cf5f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>038ca1a8-2665-4f0d-9b5b-86dfef181dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>OP</value>
      <webElementGuid>e961536c-ed92-4eb8-9bbd-20189ad9ba9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>52241b93-b4f2-4f8d-9fbd-44aea660b04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cc76f69e-6ada-46b2-bcc5-c1a3c3af6600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MISReportsForm:j_idt212_1</value>
      <webElementGuid>1fa5810a-22be-456e-85fa-a18e39704afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OP</value>
      <webElementGuid>48bc502a-190d-48e1-9542-a9512ca945b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MISReportsForm:j_idt212_1&quot;)</value>
      <webElementGuid>58703386-c062-4a84-bd7d-1419ce685a98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='MISReportsForm:j_idt212_1']</value>
      <webElementGuid>ac7c4625-c6df-4ac4-a60f-6ce4ee0c7d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='MISReportsForm:j_idt212_items']/li[2]</value>
      <webElementGuid>9e40de8a-1824-446d-9e73-ccdeb7b7462b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[7]/following::li[1]</value>
      <webElementGuid>834d3049-a47d-428c-bad5-1838b8258d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'MISReportsForm:j_idt212_1', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>dde13607-a8ba-4a47-ba16-18c104023377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IP'])[3]/preceding::li[1]</value>
      <webElementGuid>44cb312e-d3cb-4728-92b3-d78a51ea7879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ER'])[3]/preceding::li[2]</value>
      <webElementGuid>68a3bf73-4cd6-4dc1-b666-bdd481f83561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/ul/li[2]</value>
      <webElementGuid>0724d7cd-7e40-492c-b649-270c30cebb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'MISReportsForm:j_idt212_1' and (text() = 'OP' or . = 'OP')]</value>
      <webElementGuid>553f5283-82cc-484a-b409-54b723c085e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
