<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ConfirmationAre you sureYesNo</name>
   <tag></tag>
   <elementGuidId>98b7ce43-342c-4a97-9f67-e7f28a32ae01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedFacilityUserListForm:j_idt174']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7fedbf2d-368c-4487-9bbe-c96948cfcdb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedFacilityUserListForm:j_idt174</value>
      <webElementGuid>499bb419-4ec8-413d-a2a5-d48ae8841a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-confirm-dialog ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-hidden-container</value>
      <webElementGuid>b0600f53-5fd7-4819-8ced-df635f2b8242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>f17fc67e-f2ef-44ca-a467-f1824074a3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>AccumedFacilityUserListForm:j_idt174_title</value>
      <webElementGuid>c103729b-e6de-409a-aea2-adb81e097a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5bba1b49-398b-4668-a3bb-2083fb9b5809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>66ec4132-f072-4579-980b-d63b468b3f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ConfirmationAre you sure?YesNo</value>
      <webElementGuid>2bbe77a4-7f14-4d4d-9e3f-819307c71bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserListForm:j_idt174&quot;)</value>
      <webElementGuid>58cb2895-cc76-4c79-8e15-db4cc63f75dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='AccumedFacilityUserListForm:j_idt174']</value>
      <webElementGuid>3e94af18-d96a-4780-88a0-2ead043fe7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows Per Page'])[1]/following::div[5]</value>
      <webElementGuid>75857417-30d8-48b9-be06-2ac093003111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::div[5]</value>
      <webElementGuid>90119d0b-92ff-464a-a8f9-c9cb8207a46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]</value>
      <webElementGuid>ab4bd5e2-e0bb-486f-a97a-3e780a8f1e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'AccumedFacilityUserListForm:j_idt174' and (text() = 'ConfirmationAre you sure?YesNo' or . = 'ConfirmationAre you sure?YesNo')]</value>
      <webElementGuid>d6f27d53-50f3-4e82-942f-b75989c40955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
