<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_The maximum Percentage of discount ()_23843f</name>
   <tag></tag>
   <elementGuidId>ebbf4168-047c-4b98-904f-af6c6bd0c822</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff2b0ab7-45af-4060-8c5b-3c7c479ed367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input</value>
      <webElementGuid>44628072-10d3-4548-a436-28170064dbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input</value>
      <webElementGuid>9c8aec61-1366-4729-8565-1dbc6fd6ed03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9d0a755-4a3f-4895-a061-61452960129c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>a7adcf8a-0d6c-4799-bafb-331a38e6055e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>939878c7-8eac-49db-8c29-2194396ec1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>760697bc-6318-4a71-a3f6-7280f42d4492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dff20870-3c00-44ad-a862-10e40d8f93dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input&quot;)</value>
      <webElementGuid>80cbaf35-37ea-46c9-bc22-c73d38e6607b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input']</value>
      <webElementGuid>10ac21c8-da91-499b-8d2a-98196ec84ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage']/input</value>
      <webElementGuid>f6063c7f-ccb6-481d-99b5-59d550f1423d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>be38d858-f1f4-4c0d-a3b2-10c9ec88c208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input' and @name = 'AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input' and @type = 'text']</value>
      <webElementGuid>e576b790-ff94-459a-a5aa-876d0d595490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
