<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Data Entry</name>
   <tag></tag>
   <elementGuidId>ee4294cc-b9f9-4c09-8498-f57ee1a8db19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='ipactionsButtonsForm:stage_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>71d55a0f-f16d-4a54-80b4-72e455fe0fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ipactionsButtonsForm:stage_label</value>
      <webElementGuid>23be449a-9874-473d-a3b4-e2b85d098a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>5747a699-d5c6-4b25-b18a-3bf75e10d1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Entry</value>
      <webElementGuid>c5f59c02-f232-433a-b1e9-787d3ce51847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ipactionsButtonsForm:stage_label&quot;)</value>
      <webElementGuid>3c4bb9db-4633-4b5d-b25f-e4fc53754302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='ipactionsButtonsForm:stage_label']</value>
      <webElementGuid>de13855f-655e-4743-92a5-bc6a28f89f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ipactionsButtonsForm:stage']/label</value>
      <webElementGuid>559429aa-ec7a-4fd7-9e50-b4a71548c938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Stage'])[1]/following::label[1]</value>
      <webElementGuid>c6b7d051-50ce-47ff-ad99-87937e059011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::label[2]</value>
      <webElementGuid>2105b617-4659-4ddf-9b6b-9bb6b8bc0a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Status'])[1]/preceding::label[1]</value>
      <webElementGuid>f004970e-d194-41da-a6ab-9ec44f74743d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CheckIn'])[4]/preceding::label[2]</value>
      <webElementGuid>94818c8d-40d8-4a23-968f-16dc71ea1a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td[2]/div/label</value>
      <webElementGuid>588ea873-f454-445e-a61d-15e9692c4673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'ipactionsButtonsForm:stage_label' and (text() = 'Data Entry' or . = 'Data Entry')]</value>
      <webElementGuid>8361495d-c206-43dd-8dff-298ce7978ffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
