<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Data Entry</name>
   <tag></tag>
   <elementGuidId>b852333f-f53f-472d-8e40-d4581e8220aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ipactionsButtonsForm:stage_9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>89bf7672-b704-4ae6-9cf6-d77a57b9ac86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-highlight</value>
      <webElementGuid>991d331a-dc3f-46b9-99e2-56768204c91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Data Entry</value>
      <webElementGuid>5c8d0c44-590e-45a4-9586-544063b4a85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>56f473c7-6c54-4acb-be38-c98e0e29df4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e0e3846d-a91f-42a1-b1fd-170fb61fad6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ipactionsButtonsForm:stage_9</value>
      <webElementGuid>5b99a454-ab1a-42c4-8191-13e38be56192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Entry</value>
      <webElementGuid>d54d3f0e-e083-4efe-8204-4cc9ee4e738b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ipactionsButtonsForm:stage_9&quot;)</value>
      <webElementGuid>4d1a36c3-90b1-4bc6-9400-221e2421a637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ipactionsButtonsForm:stage_9']</value>
      <webElementGuid>c79e70c6-24ec-4ec3-8899-0d7cf464defd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ipactionsButtonsForm:stage_items']/li[10]</value>
      <webElementGuid>2aecc6fd-5fec-4e22-a6c5-3189202437f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coding Correction'])[4]/following::li[1]</value>
      <webElementGuid>a8707b6c-30e8-4149-b3c9-80a3d827f56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coding'])[5]/following::li[2]</value>
      <webElementGuid>df46ea58-25f9-4174-8101-c54c643f1bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deleted'])[4]/preceding::li[1]</value>
      <webElementGuid>db8ca67d-3245-4331-9640-c97b1878f56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denial Accepted'])[4]/preceding::li[2]</value>
      <webElementGuid>56dc6d24-c049-4046-96d9-aba68e6ed6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[72]/div/ul/li[10]</value>
      <webElementGuid>14b976e9-1f34-4767-b474-78cb50e2b39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ipactionsButtonsForm:stage_9' and (text() = 'Data Entry' or . = 'Data Entry')]</value>
      <webElementGuid>d87058a7-44f5-4de0-b211-622fae8c877d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
