<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_sahuyt sanyhja garam</name>
   <tag></tag>
   <elementGuidId>4f707515-44f8-4db9-a3af-08f0476b48a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='phWLForm:phWLTbl:0:patient_FullNameCol']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>289d28dd-b1b4-4c09-91e4-d8e445555049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phWLForm:phWLTbl:0:patient_FullNameCol</value>
      <webElementGuid>bc4595a1-8d49-44c1-a586-a0737cbd7ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sahuyt sanyhja garam</value>
      <webElementGuid>d33e32c5-b971-4eda-91aa-22b9bbd6a783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phWLForm:phWLTbl:0:patient_FullNameCol&quot;)</value>
      <webElementGuid>00568ab3-a071-4838-8bae-119a358b9ace</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='phWLForm:phWLTbl:0:patient_FullNameCol']</value>
      <webElementGuid>d95db37a-3508-4bd9-b18c-9bf5a30572d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='phWLForm:phWLTbl_data']/tr/td[3]/span</value>
      <webElementGuid>03fad4cf-95c8-4a3e-abe9-75f08563be7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CheckIn'])[1]/following::span[1]</value>
      <webElementGuid>06fc2832-9713-4790-9517-4bd58fa1e5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DataEntry'])[1]/following::span[2]</value>
      <webElementGuid>8f14a1a8-66c2-47aa-b1fe-4012bef636de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mrn-78//*'])[1]/preceding::span[1]</value>
      <webElementGuid>899e47c8-18c8-46df-bdea-12ff50f5bb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APM-OP-0001010'])[1]/preceding::span[2]</value>
      <webElementGuid>ace74cdd-c7df-41c5-963f-59621398e5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sahuyt sanyhja garam']/parent::*</value>
      <webElementGuid>04ef6fb3-32be-4597-b4ea-72cc8d8ecbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/table/tbody/tr/td[3]/span</value>
      <webElementGuid>35b2b720-d4fd-4bc9-908b-3400b8ba1cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'phWLForm:phWLTbl:0:patient_FullNameCol' and (text() = 'sahuyt sanyhja garam' or . = 'sahuyt sanyhja garam')]</value>
      <webElementGuid>25e5beb5-e3c0-4458-9a6b-a8fe19fd2337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
