<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KSP001Self Pay - Cash_ui-button-icon-l_b3bc42</name>
   <tag></tag>
   <elementGuidId>b30f8f35-cbff-477c-8de6-acb2fdacb6b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='phWLForm:phWLTbl:0:j_idt264']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-button-icon-left.ui-icon.ui-c.fa.fa-th-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fb2e7477-6374-4291-be9f-ed8c25c3f81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-icon-left ui-icon ui-c fa fa-th-list</value>
      <webElementGuid>77912ce7-10d4-464a-aca6-fc7d9f37dbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phWLForm:phWLTbl:0:j_idt264&quot;)/span[@class=&quot;ui-button-icon-left ui-icon ui-c fa fa-th-list&quot;]</value>
      <webElementGuid>58e4d571-3f00-436a-b3d0-855db16c1b7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='phWLForm:phWLTbl:0:j_idt264']/span</value>
      <webElementGuid>c7924129-ccbc-4dc3-b64f-0d760de7b533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[21]/button/span</value>
      <webElementGuid>2fee8415-71a4-4ae9-a1d5-9e938d7d6305</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
