<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Abbreviation_AccumedCompanies_ce4dc7</name>
   <tag></tag>
   <elementGuidId>1c300df7-19cd-468c-830e-b3ab9ccf0fbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedCompaniesProfilesCreateForm:companyAbb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2d3bfb3-5c7f-460c-bae6-12051144da3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedCompaniesProfilesCreateForm:companyAbb</value>
      <webElementGuid>ce15b1ec-8170-4722-b3d6-0f6fcc749bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedCompaniesProfilesCreateForm:companyAbb</value>
      <webElementGuid>40c80412-d335-4cea-9806-e8f9e594f592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3bcfc750-86ce-4e45-a485-6605758cee1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>e0c84c90-317c-4515-95b7-2694ec53b58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b8dd6d39-7ea5-4683-a73d-130d7f8bb9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9990ea92-f3dd-4d99-a3ba-801ce57d8bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3f233c1e-c5b7-4646-91eb-9d996095e669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedCompaniesProfilesCreateForm:companyAbb&quot;)</value>
      <webElementGuid>28a0045e-d5f7-4011-9c88-1048e391843d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedCompaniesProfilesCreateForm:companyAbb']</value>
      <webElementGuid>cdae9371-d7bd-4083-85e8-540bfc141976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AccumedCompaniesProfilesCreateForm:j_idt176']/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>00769d77-bf74-4a3f-8eba-788a9dbe3da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>9ed2286d-a101-4a3f-8045-48a553879067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedCompaniesProfilesCreateForm:companyAbb' and @name = 'AccumedCompaniesProfilesCreateForm:companyAbb' and @type = 'text']</value>
      <webElementGuid>288e1790-68c1-4411-8329-e5f538294aa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
