<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_View</name>
   <tag></tag>
   <elementGuidId>2dc418ed-924a-458d-8d06-6595ed874303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='AccumedCompaniesProfilesListForm:datalist:0:viewButton']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2ba7300d-dfd3-433a-9dcb-d49109d12303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>658cb0d5-0cdf-425e-9029-9a9c27470953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>f4187ac0-2168-4c6c-b379-09c63d927f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedCompaniesProfilesListForm:datalist:0:viewButton&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>bc4c8d89-a4b1-4668-b7a3-92fa86a32e15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='AccumedCompaniesProfilesListForm:datalist:0:viewButton']/span[2]</value>
      <webElementGuid>323c9bb1-c22c-46f5-b70a-4d52900597e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/following::span[2]</value>
      <webElementGuid>ea16108b-1375-400f-afa7-539234c11dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SANTECHTURE'])[1]/following::span[4]</value>
      <webElementGuid>e2bfdbb6-ecb0-4b39-9ddc-35280d3bd9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::span[2]</value>
      <webElementGuid>8ad6ebde-4ea9-4e70-a3ad-9054dfdf9281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ERP'])[1]/preceding::span[3]</value>
      <webElementGuid>2deacfac-1e69-4a5b-b8c9-3e333d04af22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button/span[2]</value>
      <webElementGuid>a6f57c2f-f84f-49fc-a0a9-024fabff6c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'View' or . = 'View')]</value>
      <webElementGuid>31ae56a4-692d-4580-b66b-83617257c846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
