<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_input_search advance</name>
   <tag></tag>
   <elementGuidId>b9322d7e-b539-4378-bec3-3dfbcbca8260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;collectionForm:patient_input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ccec604e-fdf4-4543-9a8b-e6e091c43c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1669279226588</value>
      <webElementGuid>4a09acb9-d9db-48b5-b663-03fbd449349b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
