<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Patient not availed service</name>
   <tag></tag>
   <elementGuidId>1e343a50-6f22-47a8-835c-aed50baa2112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='RefundAdvanceCollectionDlgForm:refundReason_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>afcfcb47-a735-44dd-9ed1-e736f7992266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>fa0300ff-6e29-414f-b001-4c5b39198ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Patient not availed service</value>
      <webElementGuid>760bee44-5c95-4023-b6ce-ce9c271b2e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>33bbc02f-e900-4e52-8061-3fece38db9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>83e88537-f53f-4267-8c10-88be7b4e7f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RefundAdvanceCollectionDlgForm:refundReason_3</value>
      <webElementGuid>aa9419ec-5b26-43f4-b8dd-cf2d32cb44e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient not availed service</value>
      <webElementGuid>0eaf8d42-69f5-49c0-9540-7245f933f00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RefundAdvanceCollectionDlgForm:refundReason_3&quot;)</value>
      <webElementGuid>62aa78ce-4488-4298-8b8c-a0d7e17f2b2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='RefundAdvanceCollectionDlgForm:refundReason_3']</value>
      <webElementGuid>65cc2c67-89a3-4363-a71b-2356b11ff714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='RefundAdvanceCollectionDlgForm:refundReason_items']/li[4]</value>
      <webElementGuid>19cbb96e-e8fe-4167-a6ea-920540048eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Others'])[2]/following::li[1]</value>
      <webElementGuid>b53f21f0-6e02-45f4-99d5-645a2f03a6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance approved the service'])[2]/following::li[2]</value>
      <webElementGuid>2cff6571-2c7f-42e3-8a82-eb84386cf881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service not available'])[2]/preceding::li[1]</value>
      <webElementGuid>41f2a061-99dd-45eb-944c-3faa449f4867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/ul/li[4]</value>
      <webElementGuid>063d13e8-214a-4349-aae1-dd717386772c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'RefundAdvanceCollectionDlgForm:refundReason_3' and (text() = 'Patient not availed service' or . = 'Patient not availed service')]</value>
      <webElementGuid>1be6dd10-52e9-4cfc-a8bc-547d97bdebb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
