<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_save</name>
   <tag></tag>
   <elementGuidId>95a43242-04cd-4b42-b611-625f59f23fe1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=&quot;InsuranceDetailsForm:j_idt1649&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0781a6e2-5eda-4098-ab4f-4496e5c89bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1669196007733</value>
      <webElementGuid>fdeb945c-231e-41c7-b82c-b7c1cfe03058</webElementGuid>
   </webElementProperties>
</WebElementEntity>
