<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cancel_InvoiceDlg_modal</name>
   <tag></tag>
   <elementGuidId>8a61b573-fa69-45db-986a-d17eaf8906e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='InvoiceDlg_modal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#InvoiceDlg_modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cb9d893d-a652-4e9c-adfe-50f214449a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceDlg_modal</value>
      <webElementGuid>46cfda10-cc04-4b62-9a99-0f322fd3582e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget-overlay ui-dialog-mask</value>
      <webElementGuid>f8fb79f7-c8a2-43c2-a401-b919df6f7c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceDlg_modal&quot;)</value>
      <webElementGuid>25c0b6b2-b54c-4e8c-89f2-9a5cb7eb55d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='InvoiceDlg_modal']</value>
      <webElementGuid>a1ae3d8b-8a66-4a96-bf1e-4fe064c266ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[77]</value>
      <webElementGuid>03b9e7a1-14eb-420d-bbef-9096a470a46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'InvoiceDlg_modal']</value>
      <webElementGuid>59d356f9-32e9-4f48-b725-774aa938880e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
