<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_National ID_AccumedPatientCreateForme_a5ef9f</name>
   <tag></tag>
   <elementGuidId>a9244181-5671-4f5e-bb48-14fc7a271855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedPatientCreateForm:emiratesId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2703535-1984-4263-8817-b8b3c9bd474f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientCreateForm:emiratesId</value>
      <webElementGuid>f2955897-5980-44c5-90c1-db5a440e86e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedPatientCreateForm:emiratesId</value>
      <webElementGuid>2c1371d4-925a-4804-984f-6de9312bf6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5a694f4-299f-4402-ab4e-1463e1f9592e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedPatientCreateForm:emiratesId&quot;,e:&quot;keyup&quot;,p:&quot;AccumedPatientCreateForm:emiratesId&quot;,u:&quot;AccumedPatientCreateForm:msgLastname AccumedPatientCreateForm:createButton&quot;});</value>
      <webElementGuid>acd99732-7e65-4383-843e-cc2755f98108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>2d747de4-655c-46e0-a35c-498687d53253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8c144adc-7e30-4458-ab8b-183a0063e6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95c58194-e8b1-461d-9838-874a232793ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>97b8294d-c9be-47f1-b324-990bd7ccef34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientCreateForm:emiratesId&quot;)</value>
      <webElementGuid>324f2d84-01c9-4395-8a56-cd9c6f0f81f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedPatientCreateForm:emiratesId']</value>
      <webElementGuid>a6abf575-e613-4a6c-aeba-e6b41113a3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AccumedPatientCreateForm:j_idt1082']/tbody/tr/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>f93b6e22-1a2f-42a1-acd0-3f2acedf951d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>4aeb9540-8a8f-4ba3-bc68-537444c39fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedPatientCreateForm:emiratesId' and @name = 'AccumedPatientCreateForm:emiratesId' and @type = 'text']</value>
      <webElementGuid>59e26d3c-b880-48e7-99b4-2f62df1c48a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
