<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_ACCIDENT  EMERGENCY</name>
   <tag></tag>
   <elementGuidId>e95aed75-e353-45f8-8cf7-b90185b65e4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='InvoiceForm:department_7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>56d541fa-875b-4dc8-9b4d-363ec69f4cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>571db3cb-45fa-4b6a-a217-eec636432235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>ACCIDENT &amp; EMERGENCY</value>
      <webElementGuid>ceedf8f2-f323-41f6-8fdf-604132c1d31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>db90f82c-1336-41de-aa10-287f0cf42713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>75269376-327c-4534-ac89-22c9d8e2664b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceForm:department_7</value>
      <webElementGuid>492749fc-3196-4b73-b9b4-bcf5fc6af804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCIDENT &amp; EMERGENCY</value>
      <webElementGuid>f5c887a5-3f80-4b4e-aacc-d9741bb4299e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceForm:department_7&quot;)</value>
      <webElementGuid>30948786-dc66-4ee0-bf4c-79b007ef17f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='InvoiceForm:department_7']</value>
      <webElementGuid>d085c89f-9074-4e09-80ff-984a360f6fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='InvoiceForm:department_items']/li[8]</value>
      <webElementGuid>5b996f70-a4b8-4c57-80cb-658780d3b5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='??????? ????????'])[4]/following::li[2]</value>
      <webElementGuid>ca5fc582-026a-43cb-bcb9-0d3a6f4d3e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADENO-TONSILLECTOMY'])[4]/preceding::li[1]</value>
      <webElementGuid>bcac5f8a-d2f4-493a-9f82-6d65de35b252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADULT DIETITAN CLNIC MALE'])[4]/preceding::li[2]</value>
      <webElementGuid>3bb677b1-264b-480a-bccb-98b08032187b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[89]/div/ul/li[8]</value>
      <webElementGuid>5687d121-360f-4758-847c-bd19d2fd6562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'InvoiceForm:department_7' and (text() = 'ACCIDENT &amp; EMERGENCY' or . = 'ACCIDENT &amp; EMERGENCY')]</value>
      <webElementGuid>112c4c6c-195e-433f-82ad-5f1492487400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
