<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Married</name>
   <tag></tag>
   <elementGuidId>e6f8063e-9d81-494e-8bf5-a0417f4fc6a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='AccumedPatientCreateForm:martial_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>152ee3e6-d166-4958-92dc-bf4faef0cdda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>c127c562-3dbb-405e-9ec0-8cbe7c225d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Married</value>
      <webElementGuid>6304a104-726d-4a85-8dc7-7b7b1f620daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>150140b8-40d3-4339-af8f-ae9e7cf8f5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4189aec8-c61f-45c2-a315-d42b879314f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientCreateForm:martial_3</value>
      <webElementGuid>23bac4e2-1891-4f3d-8b83-0589b942cb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Married</value>
      <webElementGuid>121f9d49-a1cd-4ec3-9fcd-5ad9b81cfc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientCreateForm:martial_3&quot;)</value>
      <webElementGuid>ec698b10-6271-49a1-abb5-70c17062be02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='AccumedPatientCreateForm:martial_3']</value>
      <webElementGuid>35d39979-5ab4-4f34-b816-e2e9b43def95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='AccumedPatientCreateForm:martial_items']/li[4]</value>
      <webElementGuid>e65d960d-ca56-4f28-a6e4-3ca9e3323611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legally Separated'])[4]/following::li[1]</value>
      <webElementGuid>376254b6-7075-44f1-96e4-aafd0c0ae905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Divorced'])[4]/following::li[2]</value>
      <webElementGuid>4048083b-1e3f-4c7c-8687-8f1658a80cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[5]/preceding::li[1]</value>
      <webElementGuid>72ef6376-97c3-428b-a970-2127398162b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Significant Other'])[4]/preceding::li[2]</value>
      <webElementGuid>796a2453-f847-43f2-a12a-c3f38da74cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[95]/div/ul/li[4]</value>
      <webElementGuid>262084af-5f63-4595-9b71-23b191e4843b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'AccumedPatientCreateForm:martial_3' and (text() = 'Married' or . = 'Married')]</value>
      <webElementGuid>2e20cfcf-9b39-4df5-bb7d-3f0cec23b2d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
